import mongoose, { Schema, Document } from 'mongoose';

export type UserRole = 'super_admin' | 'employee' | 'member';

export interface IUser extends Document {
  fullName: string;
  mobile: string;
  whatsapp?: string;
  email?: string;
  password?: string;
  role: UserRole;
  designation?: string; // Block Employee, District Coordinator, etc.
  employeeId?: string; // Auto-generated by Admin
  status: 'pending' | 'active' | 'inactive' | 'rejected';
  otp?: string;
  otpExpires?: Date;
  state?: string;
  district?: string;
  block?: string;
  area?: string;
  pincode?: string;
  address?: string;
  qualification?: string;
  experience?: string;
  aadhaarNumber?: string;
  profileImage?: string;
  documents?: {
    idProof?: string;
    photo?: string;
  };
  joiningDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const UserSchema: Schema = new Schema(
  {
    fullName: { type: String, required: true },
    mobile: { type: String, required: true, unique: true },
    whatsapp: { type: String },
    email: { type: String, sparse: true },
    password: { type: String },
    role: { 
      type: String, 
      enum: ['super_admin', 'employee', 'member'], 
      default: 'member' 
    },
    designation: { type: String },
    employeeId: { type: String, unique: true, sparse: true },
    status: { 
      type: String, 
      enum: ['pending', 'active', 'inactive', 'rejected'], 
      default: 'pending' 
    },
    otp: { type: String },
    otpExpires: { type: Date },
    state: { type: String },
    district: { type: String },
    block: { type: String },
    area: { type: String },
    pincode: { type: String },
    address: { type: String },
    qualification: { type: String },
    experience: { type: String },
    aadhaarNumber: { type: String },
    profileImage: { type: String },
    documents: {
      idProof: { type: String },
      photo: { type: String },
    },
    joiningDate: { type: Date },
  },
  { timestamps: true }
);

// Prevent model recompilation in development
export default mongoose.models.User || mongoose.model<IUser>('User', UserSchema);
